name: Deploy to heroku
on:
  push:
    branches:
      - deploy
    paths:
      - api/**
      - .github/workflows/back.yml
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apicodebakery" #Must be unique in Heroku
          heroku_email: "santiagorincon2001@gmail.com"
          appdir: "api"
       